# Theory

In [1]:
2 + 3

5

In [2]:
3 - 2

1

In [3]:
8 * 12

96

In [4]:
100 / 7

14.285714285714286

In [5]:
100 // 7

14

In [6]:
2 + 14* 7

100

In [7]:
5 ** 5

3125

In [8]:
((2 + 5)  * (17 - 3)) / (4**3)

1.53125

In [9]:
cost_of_ice_bag = 1.25

In [10]:
profit_margin = .2

In [11]:
number_of_bags = 500 

In [12]:
total_profit = number_of_bags*(profit_margin*cost_of_ice_bag)

In [13]:
print(total_profit)

125.0


In [14]:
print("The grocery store makes a profit of $", total_profit)

The grocery store makes a profit of $ 125.0


In [15]:
# Store input data in a variable
cost_of_ice_bag = 1.25
profit_margin = .2
number_of_bags = 500

# Perform the required calculations
profit_per_bag = cost_of_ice_bag * profit_margin
total_profit = number_of_bags * profit_per_bag

# Display the result
print("The grocery store makes a profit of $", total_profit)

The grocery store makes a profit of $ 125.0


# Operators


< , >, >= , <=, ==, and, or, not

In [16]:
3 > 6

False

In [17]:
6 > 3

True

# Python variable and datatypes

In [18]:
color1, color2, color3 = "red", "green", "blue"
print(color2)

green


In [19]:
counter = 1
counter = counter + 1
print(counter)

2


Intergers, Float, Boolean, None, String, List, Tuple, Set, Dict

In [20]:
len(color3)

4

In [21]:
list(color1)

['r', 'e', 'd']

In [22]:
today = " Saturday "

In [23]:
today[1]

'S'

In [24]:
today[3:8]

'turda'

In [25]:
today[::-1]

' yadrutaS '

In [26]:
'day' in today

True

In [27]:
full_name = "Derek"
greeting = "Hello"
new_greeting = greeting +" "+full_name
print(new_greeting)

Hello Derek


In [28]:
new_greeting.lower()

'hello derek'

In [29]:
new_greeting.replace("Hello","Wednesday")

'Wednesday Derek'

In [30]:
new_greeting.split(" ")

['Hello', 'Derek']

# Lists in Python

In [31]:
fruits = ['apple','banana','cherry']
fruits

['apple', 'banana', 'cherry']

In [32]:
type(fruits)

list

In [33]:
a_list = [23,"hello",None, 3.14,fruits, 3 <= 5]

In [34]:
a_list

[23, 'hello', None, 3.14, ['apple', 'banana', 'cherry'], True]

In [35]:
empty_list = []
len(a_list)

6

In [36]:
a_list[0]

23

In [37]:
a_list[1]

'hello'

In [38]:
a_list[-1]

True

In [39]:
a_list[2:5] 

[None, 3.14, ['apple', 'banana', 'cherry']]

In [40]:
for i in a_list:
    print(i)

23
hello
None
3.14
['apple', 'banana', 'cherry']
True


In [41]:
fruits.append("dates")

In [42]:
fruits

['apple', 'banana', 'cherry', 'dates']

In [43]:
fruits.insert(3,"Strawberry")

In [44]:
fruits

['apple', 'banana', 'cherry', 'Strawberry', 'dates']

In [45]:
'cherry' in fruits

True

In [46]:
more_fruits = fruits + fruits

In [47]:
more_fruits

['apple',
 'banana',
 'cherry',
 'Strawberry',
 'dates',
 'apple',
 'banana',
 'cherry',
 'Strawberry',
 'dates']

In [48]:
more_fruits1 = more_fruits.copy()

In [49]:
more_fruits1

['apple',
 'banana',
 'cherry',
 'Strawberry',
 'dates',
 'apple',
 'banana',
 'cherry',
 'Strawberry',
 'dates']

In [50]:
#Tuples can't be modified once they are created
tuple1 = ("apple","banana" "cherry")
type(tuple1)

tuple

In [51]:
person = {
    'name':'Srinidhi',
    'age': 24,
    'gender':'Male'
}

In [52]:
person.keys()

dict_keys(['name', 'age', 'gender'])

In [53]:
person['name']

'Srinidhi'

In [54]:
person.get('name')

'Srinidhi'

In [55]:
person[26] = "Sannidhi"
print(person)

{'name': 'Srinidhi', 'age': 24, 'gender': 'Male', 26: 'Sannidhi'}


In [56]:
person.values()

dict_values(['Srinidhi', 24, 'Male', 'Sannidhi'])

In [57]:
person.items()

dict_items([('name', 'Srinidhi'), ('age', 24), ('gender', 'Male'), (26, 'Sannidhi')])

In [58]:
for i,j in person.items():
    print(i,j)

name Srinidhi
age 24
gender Male
26 Sannidhi


### Conditional Statements

In [59]:
a_number = 34
if a_number % 2 == 0:
    print("Even")
else:
    print("Odd")

Even


# El-if is used a lot to check multiple statements

# Nested if can also be used to check diff 


In [60]:
# While and for - loops in Python

In [61]:
#factorial 
result = 1
i = 1
while i <= 5:
    result = result * i
    i += 1   #i = i + 1
print("The factorial of the number is {}".format(result))

The factorial of the number is 120


In [62]:
%%time
result = 1
i = 1
while i <= 100:
    result = result * i
    i += 1   #i = i + 1
print(result)

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000
CPU times: total: 15.6 ms
Wall time: 1.08 ms


In [63]:
line = '*'
max_len = 10
while len(line) <= max_len:
    print(line)
    line += '*'
while len(line) > 0:
    print(line)
    line = line[:-1]

*
**
***
****
*****
******
*******
********
*********
**********
***********
**********
*********
********
*******
******
*****
****
***
**
*


# Break and Continue statements 

In [76]:
i = 0
while i <= 10:
    i += 1
    if i % 2 == 0:
        print("Number is even")
        continue
    print(i)
   

1
Number is even
3
Number is even
5
Number is even
7
Number is even
9
Number is even
11


In [65]:
days = ["SUnday", "Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday"]
for day in days:
    print(day)

SUnday
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday


In [70]:
person = {
    'name':'Srinidhi',
    'sex': 'Male',
    'age':24,
    'married': False    
}
for key in person:
    print("The {} has {}".format(key,person[key]))

The name has Srinidhi
The sex has Male
The age has 24
The married has False


In [71]:
range(100)

range(0, 100)

In [72]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [73]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6


In [74]:
for i in range(1, 10, 2):
    print(i)

1
3
5
7
9


In [77]:
for day in days:
    if day == 'Wednesday':
        print("Not work wednesday")
        continue
    print(day)

SUnday
Monday
Tuesday
Not work wednesday
Thursday
Friday
Saturday


In [78]:
for day in days:
    pass

# Functions in Python

In [79]:
def say_hello():
    print("Hey!! how are you ??")

In [80]:
say_hello()

Hey!! how are you ??


In [81]:
def filter_even(number_list):
    result_list = []
    for number in number_list:
        if number % 2 == 0:
            result_list.append(number)
    return result_list
        

In [82]:
list1 = [1,2,3,4,5,6,7,8,9,10]
filter_even(list1)

[2, 4, 6, 8, 10]

In [89]:
def filter_odd(list1):
    result_odd = []
    for i in list1:
        if i % 2 != 0:
            result_odd.append(i)
    return result_odd

In [90]:
list1 = [1,2,3,4,5,6,7,8,9,10]
filter_odd(list1)

[1, 3, 5, 7, 9]

In [97]:
def loan_emi(amount):
    emi = amount/12
    print('The EMI is {}'.format(emi))

In [98]:
loan_emi(1260000)

The EMI is 105000.0


In [99]:
def loan_emi(amount, duration):
    emi = amount/ duration
    print("The EMI is ${}".format(emi))

In [100]:
loan_emi(1260000,60)

The EMI is $21000.0


In [101]:
def loan_emi(amount, duration):
    emi = amount/ duration
    return ("The EMI is ${}".format(emi))

In [102]:
loan_emi(1260000,60)

'The EMI is $21000.0'

In [105]:
def loan_emi(amount, duration, down_payment =0):
    loan_amount = amount - down_payment
    emi = loan_amount / duration
    return emi

In [108]:
emil = loan_emi(1260000,8*12,3e5)
print(emil)

10000.0


In [109]:
def loan_emi(amount, duration,rate, down_payment=0):
    loan_amount = amount -down_payment
    emi = loan_amount *rate *((1+rate)**duration) / (((1+rate)**duration))
    return emi

In [111]:
loan_emi(1260000, 10*12,0.08/12,3e5)

6400.0

In [112]:
loan_emi(1260000, 10*12,0.08/12)

8400.0

In [113]:
emil = loan_emi(amount = 1260000, duration = 8*12, rate= 0.1/12,down_payment=3e5)

In [114]:
emil

7999.999999999999

In [115]:
def round_up(x):
    return round(x)

In [116]:
round_up(6.7778)

7

In [117]:
import math
help(math.ceil)

Help on built-in function ceil in module math:

ceil(x, /)
    Return the ceiling of x as an Integral.
    
    This is the smallest integer >= x.



In [121]:
cost_of_house = 80000
home_loan_duration = 6*12
home_loan_rate = 0.07/12
home_down_payment = 0.25 * 80000
emi_house = loan_emi(amount=cost_of_house,
                    duration=home_loan_duration,
                    rate=home_loan_rate,
                    down_payment=home_down_payment)
emi_house

350.0

# Exception Handling

In [123]:
try:
    print("Now computing result")
    result = 5 / 0 # Blowingup code
    print("Computation was completed successfully")
except ZeroDivisionError:
    print("Failed to compute result because you were trying to divide by Zero")
    result = None
print(result)

Now computing result
Failed to compute result because you were trying to divide by Zero
None


In [124]:
def loan_emi(amount, duration, rate, down_payment=0):
    """Calculates the equal monthly installments for a loan"""
    loan_amount = amount - down_payment
    try:
        emi = loan_amount * rate * ((1+rate)**duration)/(((1+rate)**duration))
    except ZeroDivisionError:
        emi = loan_amount / duration
    emi = math.ceil(emi)
    return emi

# Numerical Cpmputing with Numpy Tutorial 
    

In [127]:
w1, w2, w3 = 0.3, 0.2, 0.5
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [129]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

In [130]:
weight = [w1, w2, w3]
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoen = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69,96,70]

In [131]:
def crop_yield(region,weights):
    result = 0
    for x,w in zip(region,weight):
        result += x * w
    return result

In [134]:
for i in zip(kanto, weight):
    print(i)

(73, 0.3)
(67, 0.2)
(43, 0.5)


In [135]:
for a,b in zip(kanto,weight):
    print(a)
    print(b)

73
0.3
67
0.2
43
0.5


In [136]:
crop_yield(kanto,weight)

56.8

In [137]:
crop_yield(johto,weight)

76.9

In [138]:
crop_yield(unova,weight)

74.9

In [139]:
import numpy as np
kanto = np.array([73,67,43])

In [140]:
kanto

array([73, 67, 43])

In [141]:
weight = np.array([w1, w2, w3])

In [142]:
weight

array([0.3, 0.2, 0.5])

In [143]:
type(kanto)

numpy.ndarray

In [144]:
kanto.ndim

1

In [145]:
kanto.shape

(3,)

In [146]:
kanto.size

3

In [147]:
kanto.all

<function ndarray.all>

In [148]:
kanto.dtype

dtype('int32')

In [149]:
kanto[2]

43

In [150]:
kanto[1]

67

In [151]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    It uses an optimized BLAS library when possible (see `numpy.linalg`).
    
    Parameters
    ----------
    a 

In [152]:
type(kanto)

numpy.ndarray

In [153]:
np.dot(kanto,weight)

56.8

In [154]:
(kanto * weight).sum()

56.8

In [155]:
kanto * weight

array([21.9, 13.4, 21.5])

In [200]:
arr1 = list(range(100000))

In [201]:
arr2 = list(range(100000,200000))

In [202]:
arr1_np = np.array(arr1)

In [203]:
arr2_np = np.array(arr2)

In [204]:
%%time
result = 0
for a,b in zip(arr1,arr2):
    result += a * b
result

CPU times: total: 0 ns
Wall time: 35.5 ms


833323333350000

In [205]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 0 ns


893678192

In [206]:
(arr1_np * arr2_np).sum()

893678192

# Multi-dimension array

In [208]:
climate_data =np.array([[73,67,43],
                      [91,88,64],
                      [87,134,58],
                      [102,43,37],
                      [69,96,70]])

In [209]:
climate_data.dtype

dtype('int32')

In [210]:
climate_data.ndim

2

In [211]:
climate_data.shape

(5, 3)

In [212]:
climate_data.size

15

In [213]:
climate_data.sum

<function ndarray.sum>

In [214]:
arr3 = np.array([[[11,12,13],
                 [13,14,15]],
                
                [[15,16,17],
                [17,18,19]]])

In [215]:
arr3

array([[[11, 12, 13],
        [13, 14, 15]],

       [[15, 16, 17],
        [17, 18, 19]]])

In [216]:
arr3.ndim

3

In [217]:
arr3.shape

(2, 2, 3)

In [218]:
arr3.dtype

dtype('int32')

In [219]:
weight.dtype

dtype('float64')

In [220]:
climate_data.dtype

dtype('int32')

In [235]:
arr4 = np.array([[[11,12,13],
                 [13,14,15]],
                
                [[15,16,17],
                [17,18,19.4]]])

In [222]:
type(arr4)

numpy.ndarray

In [223]:
arr4.ndim

3

In [234]:
arr4.dtype # when last element was just 19 

dtype('int32')

In [236]:
arr4.dtype

dtype('float64')

In [240]:
np.matmul(climate_data,weight)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [241]:
np.matmul(climate_data,weight).sum()

348.20000000000005

In [359]:
np.dot(climate_data,weight)

array([2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2,
       5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2,
       8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2,
       5.2, 8.2, 5.2, 8.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2,
       5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2,
       8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2,
       2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2,
       5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2,
       8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2,
       2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2, 2.2,
       5.2, 8.2, 2.2, 5.2, 8.2, 2.2, 5.2, 8.2])

In [242]:
climate_data @ weight

array([56.8, 76.9, 81.9, 57.7, 74.9])

# Working with CSV data files

In [258]:
import urllib.request
urllib.request.urlretrieve(
'https://corgis-edu.github.io/corgis/datasets/csv/weather/weather.csv','climate2.txt')
climate_data = np.genfromtxt('climate.txt',delimiter=',',skip_header=0)
climate_data

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [4., 5., 6.],
       [7., 8., 9.],
       [4., 5., 6.],
       [7., 8., 9.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8

In [259]:
climate_data.shape

(138, 3)

In [261]:
weight = np.array([0.3,0.2,0.5])

In [262]:
yields = climate_data @ weight

In [265]:
yields.sum()

726.5999999999999

In [266]:
yields.shape

(138,)

In [267]:
climate_results = np.concatenate((climate_data,yields.reshape(138,1)),axis= 1)

In [268]:
climate_results

array([[1. , 2. , 3. , 2.2],
       [4. , 5. , 6. , 5.2],
       [7. , 8. , 9. , 8.2],
       [1. , 2. , 3. , 2.2],
       [4. , 5. , 6. , 5.2],
       [7. , 8. , 9. , 8.2],
       [1. , 2. , 3. , 2.2],
       [4. , 5. , 6. , 5.2],
       [7. , 8. , 9. , 8.2],
       [1. , 2. , 3. , 2.2],
       [4. , 5. , 6. , 5.2],
       [7. , 8. , 9. , 8.2],
       [1. , 2. , 3. , 2.2],
       [4. , 5. , 6. , 5.2],
       [7. , 8. , 9. , 8.2],
       [1. , 2. , 3. , 2.2],
       [4. , 5. , 6. , 5.2],
       [7. , 8. , 9. , 8.2],
       [1. , 2. , 3. , 2.2],
       [4. , 5. , 6. , 5.2],
       [7. , 8. , 9. , 8.2],
       [1. , 2. , 3. , 2.2],
       [4. , 5. , 6. , 5.2],
       [7. , 8. , 9. , 8.2],
       [1. , 2. , 3. , 2.2],
       [4. , 5. , 6. , 5.2],
       [7. , 8. , 9. , 8.2],
       [1. , 2. , 3. , 2.2],
       [4. , 5. , 6. , 5.2],
       [7. , 8. , 9. , 8.2],
       [1. , 2. , 3. , 2.2],
       [4. , 5. , 6. , 5.2],
       [7. , 8. , 9. , 8.2],
       [1. , 2. , 3. , 2.2],
       [4. , 5

In [270]:
np.savetxt('climate_results.txt', climate_results, fmt='%.2f',header='temp,rainfall,humidity,yield_calc',comments = '')

In [273]:
np.max(climate_results)

9.0

In [278]:
np.mean(climate_results)

5.1152173913043475

In [279]:
arr1_np

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [280]:
arr1_np + arr2_np

array([100000, 100002, 100004, ..., 299994, 299996, 299998])

In [281]:
arr1_np + 3

array([     3,      4,      5, ..., 100000, 100001, 100002])

In [282]:
arr2_np - arr1_np

array([100000, 100000, 100000, ..., 100000, 100000, 100000])

In [283]:
arr2_np / 2

array([50000. , 50000.5, 50001. , ..., 99998.5, 99999. , 99999.5])

In [284]:
arr1_np * arr2_np

array([          0,      100001,      200004, ..., -1475736471,
       -1475436476, -1475136479])

In [286]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2],
                [3,4]])
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [289]:
arr1 = np.array([1,2])
arr2 = np.array([[1,2],
                [3,4]])
arr1 + arr2

array([[2, 4],
       [4, 6]])

In [291]:
arr1 > arr2

array([[False, False],
       [False, False]])

In [292]:
arr1 == arr2

array([[ True,  True],
       [False, False]])

In [293]:
(arr1 == arr2).sum()

2

In [322]:
arr3 = np.array([[[11,12,13,14],
                [15,16,17,18]],
                
               [[15,16,23,24],
                [19,20,21,22]]])

In [323]:
arr3.shape

(2, 2, 4)

In [328]:
arr3[1,1,3]

22

In [325]:
for i in arr3:
    print(i)

[[11 12 13 14]
 [15 16 17 18]]
[[15 16 23 24]
 [19 20 21 22]]


In [329]:
arr3[1:]

array([[[15, 16, 23, 24],
        [19, 20, 21, 22]]])

In [331]:
arr3[1:,0:1,:2].shape

(1, 1, 2)

In [332]:
arr3[1:,0:1,:2]

array([[[15, 16]]])

In [334]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [335]:
np.ones([2,2,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [336]:
np.random.randint(5)

4

In [339]:
g = np.random.randn(5,6)

In [340]:
np.mean(g)

0.10149940568536933

In [341]:
np.full([2,3],56)

array([[56, 56, 56],
       [56, 56, 56]])

In [343]:
np.arange(10,90,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82])

In [345]:
np.arange(10,90,8).shape

(10,)

In [352]:
np.arange(10,90,8).reshape(2,5)

array([[10, 18, 26, 34, 42],
       [50, 58, 66, 74, 82]])

In [353]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

CPU times: total: 0 ns
Wall time: 0 ns


# Reading feom and writing to files using Python

In [360]:
import os

In [361]:
os.getcwd()

'C:\\Users\\10693867\\Downloads\\My Projects'

In [363]:
help(os.listdir)

Help on built-in function listdir in module nt:

listdir(path=None)
    Return a list containing the names of the files in the directory.
    
    path can be specified as either str, bytes, or a path-like object.  If path is bytes,
      the filenames returned will also be bytes; in all other circumstances
      the filenames returned will be str.
    If path is None, uses the path='.'.
    On some platforms, path may also be specified as an open file descriptor;\
      the file descriptor must refer to a directory.
      If this functionality is unavailable, using it raises NotImplementedError.
    
    The list is in arbitrary order.  It does not include the special
    entries '.' and '..' even if they are present in the directory.



In [364]:
os.listdir('.')

['.git',
 '.ipynb_checkpoints',
 'climate.txt',
 'climate_results.txt',
 'Covid-19 Data Analysis.ipynb',
 'MasteringPythonDataSciencePackages.ipynb',
 'MasteringPythonZeroToHero.ipynb',
 'myDataSciencePractice.ipynb',
 'myUniversalFunctions.ipynb']

In [366]:
os.makedirs('./data',exist_ok=True)

In [367]:
'data' in os.listdir('.')

True

In [368]:
os.listdir('./data')

[]

In [369]:
url3 = 'https://filesamples.com/samples/document/txt/sample3.txt'
url2 ='https://filesamples.com/samples/document/txt/sample2.txt'
url1 ='https://filesamples.com/samples/document/txt/sample1.txt'

In [370]:
import urllib.request

In [372]:
urllib.request.urlretrieve(url1,'./data/sample1.txt')
urllib.request.urlretrieve(url2,'./data/sample2.txt')
urllib.request.urlretrieve(url3,'./data/sample3.txt')

HTTPError: HTTP Error 403: Forbidden

In [388]:
file1 = open('./data/sample1.txt',mode= 'r')

In [389]:
file1_contents = file1.read()

In [390]:
print(file1_contents)


My Name is Pythonnnnnnnnn



In [392]:
file1.read()

''

In [393]:
file1.close()

In [395]:
with open('./data/sample1.txt','r') as file2:
    file2_contents = file2.read()
    print(file2_contents)

My Name is Pythonnnnnnnnn



In [396]:
with open('./data/sample1.txt','r') as file3:
    file3_lines = file3.readlines()

In [397]:
file3_lines

['My Name is Pythonnnnnnnnn\n']

In [398]:
file3_lines[0].strip()

'My Name is Pythonnnnnnnnn'

In [399]:
os.makedirs('./data/sample2.txt',exist_ok=True)

In [408]:
file4 = open('./data/sample2.txt','w')
file4.write("Srinidhi")

8

In [410]:
file4 = open('./data/sample2.txt','r')
print(file4.read())
file4.close()

Srinidhi


In [446]:
with open('./data/data3.txt','r') as file5:
    file5_cont = file5.readlines()
    print(file5_cont)

['amount,duration,rate,down_payment,\n', '828400,120,0.11,100000,\n', '4633400,240,0.06,\n', '42900,90,0.08,8900,\n', '983000,16,0.14,\n', '15230,48,0.07,4300,\n']


In [455]:
for i in file5_cont:
    print(i)

amount,duration,rate,down_payment,

828400,120,0.11,100000,

4633400,240,0.06,

42900,90,0.08,8900,

983000,16,0.14,

15230,48,0.07,4300,



In [456]:
 file#file5_cont[0]

'amount,duration,rate,down_payment,\n'

In [448]:
print(file5_cont)

['amount,duration,rate,down_payment,\n', '828400,120,0.11,100000,\n', '4633400,240,0.06,\n', '42900,90,0.08,8900,\n', '983000,16,0.14,\n', '15230,48,0.07,4300,\n']


In [434]:
f3 = open('./data/data3.txt','r')
f2 = f3.readlines()
f2

['amount,duration,rate,down_payment\n',
 '828400,120,0.11,100000\n',
 '4633400,240,0.06\n',
 '42900,90,0.08,8900\n',
 '983000,16,0.14\n',
 '15230,48,0.07,4300\n']

In [435]:
f4 =f2[0].strip()

In [437]:
f2

['amount,duration,rate,down_payment\n',
 '828400,120,0.11,100000\n',
 '4633400,240,0.06\n',
 '42900,90,0.08,8900\n',
 '983000,16,0.14\n',
 '15230,48,0.07,4300\n']

In [459]:
f2[0].split(',')

['amount', 'duration', 'rate', 'down_payment\n']

In [460]:
def parse_headers(header_line):
    return header_line.strip().split(',')

In [461]:
f2[0]

'amount,duration,rate,down_payment\n'

In [462]:
headers = parse_headers(f2[0])
headers

['amount', 'duration', 'rate', 'down_payment']

In [463]:
def parse_values(data_line):
    values = []
    for item in data_line.strip().split(','):
        values.append(float(item))
    return values

In [464]:
f2[2]

'4633400,240,0.06\n'

In [465]:
parse_values(f2[2])

[4633400.0, 240.0, 0.06]

In [466]:
parse_values(f2[1])

[828400.0, 120.0, 0.11, 100000.0]

# Analyzing tabular data using Pandas

In [473]:
from urllib.request import urlretrieve

In [474]:
urlretrieve('https://github.com/nlihin/data-analytics/blob/main/datasets/italy-covid-daywise.csv')
#https://github.com/nlihin/data-analytics/blob/main/datasets/italy-covid-daywise.csv

('C:\\Users\\10693867\\AppData\\Local\\Temp\\tmpmyw25vca',
 <http.client.HTTPMessage at 0x1f664e9da10>)

In [475]:
urlretrieve

<function urllib.request.urlretrieve(url, filename=None, reporthook=None, data=None)>

In [476]:
import pandas as pd

In [ ]:
covid_df